name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run:

    runs-on: ubuntu-24.04
    strategy:
      matrix:
        operating-system: [ubuntu-24.04]
        php-versions: ['7.4','8.0','8.3','8.5']
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

    - name: Setup PHP
      uses: setup-php/setup-php@46ae35f3338b644fa11efcbbcd5d739c34372ae8
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, pdo, pdo_mysql, intl, zip
        coverage: none

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5
      with:
        path: vendor
        key: ${{ runner.os }}-${{ matrix.php-versions }}-php-${{ hashFiles('**/composer.json') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.php-versions }}-php-
    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run test suite
      run: composer run-script test
