name: Code style and static analysis

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    run:

        runs-on: ubuntu-24.04
        strategy:
            matrix:
                operating-system: [ubuntu-24.04]
                php-versions: ['7.4','8.0', '8.3', '8.5']
        name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}

        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

            - name: Setup PHP
              uses: setup-php/setup-php@46ae35f3338b644fa11efcbbcd5d739c34372ae8
              with:
                  php-version: ${{ matrix.php-versions }}
                  extensions: mbstring, pdo, pdo_mysql, intl, zip
                  coverage: none

            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
              with:
                  path: vendor
                  key: ${{ runner.os }}-${{ matrix.php-versions }}-php-${{ hashFiles('**/composer.json') }}
                  restore-keys: |
                    ${{ runner.os }}-${{ matrix.php-versions }}-php-

            - name: Install dependencies
              if: steps.composer-cache.outputs.cache-hit != 'true'
              run: composer install --prefer-dist --no-progress --no-suggest

            - name: Run PHP-CS-Fixer
              run: composer run-script phpcs --  --dry-run
